Object.assign(window.gameData, { BarbershopItems: [
  {
    "label": "Под ноль",
    "value": 0,
    "gender": "male",
    "categoryId": 1,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Под ноль",
    "value": 0,
    "gender": "female",
    "categoryId": 1,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Коротко",
    "value": 1,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Коротко",
    "value": 1,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Ястреб",
    "value": 2,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Слои",
    "value": 2,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Хипстер",
    "value": 3,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички",
    "value": 3,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Челка набок",
    "value": 4,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Хвост",
    "value": 4,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Коротко",
    "value": 5,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Ирокез",
    "value": 5,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Байкер",
    "value": 6,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички",
    "value": 6,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Хвост",
    "value": 7,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Боб",
    "value": 7,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички",
    "value": 8,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Ястреб",
    "value": 8,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Прилиза",
    "value": 9,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Ракушка",
    "value": 9,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Коротко",
    "value": 10,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Лонг боб",
    "value": 10,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Шипы",
    "value": 11,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Свободно",
    "value": 11,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Цезарь",
    "value": 12,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Пикси",
    "value": 12,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Чоппи",
    "value": 13,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Подбритые виски",
    "value": 13,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Дреды",
    "value": 14,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Узел",
    "value": 14,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Длинные",
    "value": 15,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Волнистый боб",
    "value": 15,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Лохматые кудри",
    "value": 16,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Красотка",
    "value": 16,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Серфингист",
    "value": 17,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Пучок",
    "value": 17,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Набок",
    "value": 18,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Флэппер боб",
    "value": 18,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Зализ",
    "value": 19,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Тугой узел",
    "value": 19,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Длинные",
    "value": 20,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Одуванчик",
    "value": 20,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Юный хипстер",
    "value": 21,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Взрыв",
    "value": 21,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Маллет",
    "value": 22,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Узел",
    "value": 22,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Маллет",
    "value": 23,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Классические косички",
    "value": 24,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-пальма",
    "value": 25,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Сколотые косички",
    "value": 25,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-молнии",
    "value": 26,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-листья",
    "value": 26,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Зачесанные наверх косички",
    "value": 27,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-зигзаги",
    "value": 27,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-зигзаги",
    "value": 28,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Хвостики с челкой",
    "value": 28,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-улитки",
    "value": 29,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-волны",
    "value": 29,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Хай-топ",
    "value": 30,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Косички-завитки",
    "value": 30,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Растрепанный зачес назад",
    "value": 31,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Челка-валик",
    "value": 31,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Подстриженный зачес назад",
    "value": 32,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Растрепанный зачес назад",
    "value": 32,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Подстриженный зачес набок",
    "value": 33,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Подстриженный зачес назад",
    "value": 33,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Шипастый ирокез",
    "value": 34,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Подстриженный зачес набок",
    "value": 34,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Стиляга",
    "value": 35,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Шипастый ирокез",
    "value": 35,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Стиляга со слоями",
    "value": 36,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Бандана и косички",
    "value": 36,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Челси",
    "value": 37,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Стиляга со слоями",
    "value": 38,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Ежик",
    "value": 72,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Армейская стрижка",
    "value": 73,
    "gender": "male",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Опрятный пучок",
    "value": 76,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Короткий боб",
    "value": 77,
    "gender": "female",
    "categoryId": 1,
    "flag": 3,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": true,
    "hasOpacity": false
  },
  {
    "label": "Гладкая кожа",
    "value": 255,
    "categoryId": 2,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Легкая щетина",
    "value": 0,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Бальбо",
    "value": 1,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Круглая борода",
    "value": 2,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Эспаньолка",
    "value": 3,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Козлиная бородка",
    "value": 4,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Островок",
    "value": 5,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тонкая бородка",
    "value": 6,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Короткая бородка",
    "value": 7,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Мушкетер",
    "value": 8,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Усы",
    "value": 9,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Подстриженная борода",
    "value": 10,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Щетина",
    "value": 11,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Круглая борода",
    "value": 12,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Борода-подкова",
    "value": 13,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Карандашные усы и баки",
    "value": 14,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Борода-ремень",
    "value": 15,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Бальбо и баки",
    "value": 16,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Баки",
    "value": 17,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Короткая бородка",
    "value": 18,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Дали",
    "value": 19,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Дали и борода",
    "value": 20,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Велосипедный руль",
    "value": 21,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Островок с усами",
    "value": 22,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Английские усы с пеньком",
    "value": 23,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Голливудская борода",
    "value": 24,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Фу Манчу",
    "value": 25,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Островок с баками",
    "value": 26,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Широкие баки",
    "value": 27,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Борода `Ширма`",
    "value": 28,
    "categoryId": 2,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Нет",
    "value": 255,
    "categoryId": 3,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Аккуратные",
    "value": 0,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Модные",
    "value": 1,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Клеопатра",
    "value": 2,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Ироничные",
    "value": 3,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Женственные",
    "value": 4,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Обольстительные",
    "value": 5,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Нахмуренные",
    "value": 6,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Чикса",
    "value": 7,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Торжествующие",
    "value": 8,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Беззаботные",
    "value": 9,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Дугой",
    "value": 10,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Мышка",
    "value": 11,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Двойная высечка",
    "value": 12,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Впалые",
    "value": 13,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Нарисованные карандашом",
    "value": 14,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Выщипанные",
    "value": 15,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Прямые и тонкие",
    "value": 16,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Естественные",
    "value": 17,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Пышные",
    "value": 18,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Неопрятные",
    "value": 19,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Широкие",
    "value": 20,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Обычные",
    "value": 21,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Южноевропейские",
    "value": 22,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Ухоженные",
    "value": 23,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Кустистые",
    "value": 24,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Перышки",
    "value": 25,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Колючие",
    "value": 26,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Сросшиеся",
    "value": 27,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Крылатые",
    "value": 28,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тройная высечка",
    "value": 29,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Высечка дугой",
    "value": 30,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Подрезанные",
    "value": 31,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Сходящие на нет",
    "value": 32,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Высечка",
    "value": 33,
    "categoryId": 3,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Бритая",
    "value": 255,
    "categoryId": 4,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Естественные",
    "value": 0,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Полоска",
    "value": 1,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Дерево",
    "value": 2,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Волосатая",
    "value": 3,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Заросшая",
    "value": 4,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Обезьяна",
    "value": 5,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Причесанная обезьяна",
    "value": 6,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Бикини",
    "value": 7,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Молния",
    "value": 8,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Обратная молния",
    "value": 9,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Сердечко",
    "value": 10,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Усы",
    "value": 11,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Смайлик",
    "value": 12,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Череп",
    "value": 13,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тропинка",
    "value": 14,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тропинка и соски",
    "value": 15,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Волосатые руки",
    "value": 16,
    "categoryId": 4,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Зелёный",
    "value": 0,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Изумрудный",
    "value": 1,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Голубой",
    "value": 2,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Синий",
    "value": 3,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Светлый шатен",
    "value": 4,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Темно-коричневый",
    "value": 5,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Карий",
    "value": 6,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Темно-серый",
    "value": 7,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Светло-серый",
    "value": 8,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Розовый",
    "value": 9,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Жёлтый",
    "value": 10,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Пурпурный",
    "value": 11,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Затемнённый",
    "value": 12,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Оттенки серого",
    "value": 13,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Восходящее солнце",
    "value": 14,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Радиационный",
    "value": 15,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Искривлённый",
    "value": 16,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Е-Кола",
    "value": 17,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Космический рейнджер",
    "value": 18,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Инь и ян",
    "value": 19,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Мишень",
    "value": 20,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Ящерица",
    "value": 21,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Дракон",
    "value": 22,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Внеземной",
    "value": 23,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Козел",
    "value": 24,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Смайлик",
    "value": 25,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Одержимый",
    "value": 26,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Демон",
    "value": 27,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Инфицированный",
    "value": 28,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Пришелец",
    "value": 29,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Нежить",
    "value": 30,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Зомби",
    "value": 31,
    "categoryId": 5,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Нет",
    "value": 255,
    "categoryId": 6,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Поцелуй мой топор",
    "value": 16,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Пандочка",
    "value": 17,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Летучая мышь",
    "value": 18,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Алый череп",
    "value": 19,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Рептилия",
    "value": 20,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Вельд",
    "value": 21,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Трайбл - линии",
    "value": 26,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Трайбл - завитки",
    "value": 27,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Трайбл - оранжевый",
    "value": 28,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Трайбл - красный",
    "value": 29,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "В коробке",
    "value": 30,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Клоун",
    "value": 31,
    "categoryId": 6,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Волны слева",
    "value": -7,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Волны справа",
    "value": -8,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тотем",
    "value": -9,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Полосы слева",
    "value": -10,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Полосы справа",
    "value": -11,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Разводы налево",
    "value": -12,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Разводы направо",
    "value": -13,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "С узором налево",
    "value": -14,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "С узором направо",
    "value": -15,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Полосы",
    "value": -16,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Старейшина",
    "value": -17,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Вертикальная полоса",
    "value": -18,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Племя",
    "value": -19,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Подтеки справа",
    "value": -20,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Подтеки слева",
    "value": -21,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Феникс",
    "value": -22,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Предок",
    "value": -23,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Боевой окрас",
    "value": -24,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Симметрия",
    "value": -25,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Отпечатки пальцев",
    "value": -26,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тотемный окрас",
    "value": -27,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Дух",
    "value": -28,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Полосы на щеках",
    "value": -29,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Демон",
    "value": -30,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "В пол-лица",
    "value": -31,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Маска",
    "value": -32,
    "categoryId": 6,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Нет",
    "value": 255,
    "categoryId": 8,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Полный",
    "value": 0,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Под углом",
    "value": 1,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Округлый",
    "value": 2,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Горизонтальный",
    "value": 3,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "На скулах",
    "value": 4,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Красотка",
    "value": 5,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "В стиле 80-х",
    "value": 6,
    "categoryId": 8,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Нет",
    "value": 255,
    "categoryId": 9,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Дымчато-черный",
    "value": 0,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Бронзовый",
    "value": 1,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Мягкий серый",
    "value": 2,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Ретро-гламур",
    "value": 3,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Естественный",
    "value": 4,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Кошачьи глаза",
    "value": 5,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Чикса",
    "value": 6,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Вамп",
    "value": 7,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Вайнвудский гламур",
    "value": 8,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Баблгам",
    "value": 9,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Мечта о море",
    "value": 10,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Пин-ап",
    "value": 11,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Лиловая страсть",
    "value": 12,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Дымчатые кошачьи глаза",
    "value": 13,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Огненный рубин",
    "value": 14,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Эстрадная принцеcса",
    "value": 15,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Тушь для глаз",
    "value": 32,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Кровавые слезы",
    "value": 34,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Хеви-метал",
    "value": 35,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Печаль",
    "value": 36,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Князь тьмы",
    "value": 37,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Рокер",
    "value": 38,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Гот",
    "value": 39,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Панк",
    "value": 40,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Сокрушенность",
    "value": 41,
    "categoryId": 9,
    "flag": 4,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Нет",
    "value": 255,
    "categoryId": 10,
    "flag": 0,
    "price": 10,
    "hasColor": false,
    "hasSecondaryColor": false,
    "hasOpacity": false
  },
  {
    "label": "Цветные матовые",
    "value": 0,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Цветные блестящие",
    "value": 1,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Контур, матовые",
    "value": 2,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Контур, блестящие",
    "value": 3,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Жирный контур, матовые",
    "value": 4,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Жирный контур, блестящие",
    "value": 5,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Некрашен., контур, матовые",
    "value": 6,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Некрашеные, контур, блеск",
    "value": 7,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Размазанная помада",
    "value": 8,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  },
  {
    "label": "Гейша",
    "value": 9,
    "categoryId": 10,
    "flag": 5,
    "price": 10,
    "hasColor": true,
    "hasSecondaryColor": false,
    "hasOpacity": true
  }
]});
