Object.assign(
  window.gameData,
  {
    InteriorPropShopProducts: [
      {
        id: 10,
        categoryId: 9,
        hash: 1385634399,
        label: 'Телевизор LG',
        subLabel: 'Классика',
        price: 1000,
      },
      {
        id: 24,
        categoryId: 9,
        hash: 474767777,
        label: 'Телевизор PHILIPS',
        subLabel: 'Соверменный стиль',
        price: 10000,
      },
      {
        id: 18,
        categoryId: 1,
        hash: 1207059496,
        label: 'Лампа LUXA',
        subLabel: 'Соверменный стиль',
        price: 10000,
      },
      {
        id: 19,
        categoryId: 1,
        hash: 775684762,
        label: 'Светильник декоративный DIODÈ',
        subLabel: 'Кот с ножом, Прозрачный',
        price: 3762,
      },
      {
        id: 20,
        categoryId: 1,
        hash: 89806285,
        label: 'Светильник ночник Свеча',
        subLabel: 'Соверменный стиль',
        price: 482,
      },
      {
        id: 21,
        categoryId: 2,
        hash: 1913408338,
        label: 'Кожаный диван',
        subLabel: 'Соверменный стиль',
        price: 9500,
      },
      {
        id: 22,
        categoryId: 2,
        hash: 1992466891,
        label: 'Мягкое кресло',
        subLabel: 'Соверменный стиль',
        price: 4500,
      },
      {
        id: 27,
        categoryId: 2,
        hash: 395253250,
        label: 'Кресло - ковать',
        subLabel: 'Соверменный стиль',
        price: 10000,
      },
      {
        id: 28,
        categoryId: 2,
        hash: 1095483928,
        label: 'Замшевый багровый диван',
        subLabel: 'Соверменный стиль',
        price: 9300,
      },
      {
        id: 30,
        categoryId: 2,
        hash: 757985993,
        label: 'Кресло качалка',
        subLabel: 'Соверменный стиль',
        price: 7250,
      },
      {
        id: 31,
        categoryId: 2,
        hash: 912009140,
        label: 'Кровать с матрасом',
        subLabel: 'Соверменный стиль',
        price: 8000,
      },
      {
        id: 32,
        categoryId: 2,
        hash: 916694533,
        label: 'Матрас - кровать',
        subLabel: 'Соверменный стиль',
        price: 10000,
      },
      {
        id: 33,
        categoryId: 2,
        hash: 1114655569,
        label: 'Зеленый диван из экокожи',
        subLabel: 'Соверменный стиль',
        price: 14200,
      },
      {
        id: 34,
        categoryId: 2,
        hash: 1463409943,
        label: 'Красное кресло в старом стиле',
        subLabel: 'Соверменный стиль',
        price: 22500,
      },
      {
        id: 35,
        categoryId: 2,
        hash: 234567,
        label: 'Черное классическое кресло',
        subLabel: 'Соверменный стиль',
        price: 11900,
      },
      {
        id: 36,
        categoryId: 2,
        hash: 559308903,
        label: 'Кожаный диван с узорами',
        subLabel: 'Соверменный стиль',
        price: 17500,
      },
      {
        id: 37,
        categoryId: 2,
        hash: 1303752660,
        label: 'Кожаная скамья',
        subLabel: 'Соверменный стиль',
        price: 5200,
      },
      {
        id: 38,
        categoryId: 2,
        hash: 1063124789,
        label: 'Замшевый стул',
        subLabel: 'Соверменный стиль',
        price: 9800,
      },
      {
        id: 39,
        categoryId: 2,
        hash: 1004996711,
        label: 'Угловой диван из ткани',
        subLabel: 'Соверменный стиль',
        price: 15250,
      },
      {
        id: 40,
        categoryId: 2,
        hash: 1457686595,
        label: 'Угловой диван из ткани зеленый',
        subLabel: 'Соверменный стиль',
        price: 15000,
      },
    ],
  },
);
// EOF
